### ISSUE TITLE
DefaultRabbitListenerExceptionHandler conflicts with other RabbitListenerExceptionHandler implementations

### ISSUE THREAD

**Issue by danbsts** [micronaut-projects/micronaut-rabbitmq#114]
Hi,

An error is being thrown when trying to initialize my application using a `@RabbitListener` that tries to reach an instance inside a docker container. But when `docker-compose up` is run, it takes a while until RabbitMQ is ready and start answering requests.
The application get's ready first and tries to reach RabbitMQ and consume it's message throwing the following error and stack trace:

```
13:40:37.703 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error processing bean [Definition: com.myapp.submission.rabbitmq.SubmissionListener] method definition [void getSubmissionStatus(SubmissionStatus submissionStatus)]: Failed to retrieve a channel pool named [default] to register a listener
io.micronaut.context.exceptions.BeanContextException: Error processing bean [Definition: com.myapp.submission.rabbitmq.SubmissionListener] method definition [void getSubmissionStatus(SubmissionStatus submissionStatus)]: Failed to retrieve a channel pool named [default] to register a listener
        at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:92)
        at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:45)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1770)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2748)
        at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2637)
        at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:654)
        at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:641)
        at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$30(DefaultBeanContext.java:1431)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1430)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2568)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:202)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:188)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
        at com.myapp.Application.main(Application.java:8)
Caused by: io.micronaut.messaging.exceptions.MessageListenerException: Failed to retrieve a channel pool named [default] to register a listener
        at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:121)
        at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:64)
        at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
        ... 17 common frames omitted
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error creating connection to RabbitMQ
        at io.micronaut.configuration.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:63)
        at io.micronaut.configuration.rabbitmq.connect.$RabbitConnectionFactory$Connection0Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:125)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1714)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2428)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2414)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2105)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2079)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1113)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:626)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:114)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1714)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2428)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2414)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2105)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2079)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:616)
        at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:119)
        ... 19 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
        at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1106)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1021)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1213)
        at io.micronaut.configuration.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:60)
        ... 36 common frames omitted
```

Micronaut's documentation, as stated in [7.2 Handling Consumer Exceptions](https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/index.html#consumerExceptions), says that we might be allowed to change the default implementation of a `RabbitListenerExceptionHandler` with our own, but the `DefaultRabbitListenerExceptionHandler` is marked as `@Primary` leading to a `NonUniqueBeanException`.

https://github.com/micronaut-projects/micronaut-rabbitmq/blob/d1244973f9079c72755da4055aa58350536e7047/rabbitmq/src/main/java/io/micronaut/configuration/rabbitmq/exception/DefaultRabbitListenerExceptionHandler.java#L35

I was wondering if this is the expected behavior for application initialization (since it should crash if doesn't reach the RabbitMQ) or if the developer should be able to change its implementation and trigger a reconnect then delay the application startup.

This is a code example of how to trigger the related behavior (in case I'm missing something):

SubmissionListener
```Java
//@Primary // uncomment this line to throw NonUniqueBeanException
@RabbitListener
public class SubmissionListener implements RabbitListenerExceptionHandler {
  private static final Logger LOG = LoggerFactory.getLogger(SubmissionListener.class);

  @Inject private SubmissionFacade submissionFacade;

  @Queue(value = "submissions-status")
  public void getSubmissionStatus(SubmissionStatus submissionStatus) {
    submissionFacade.updateSubmissionStatus(submissionStatus);
  }

  @Override
  public void handle(RabbitListenerException exception) {
    LOG.error("Testing error handler");
  }
}
```

ChannelPoolListener
```Java
@Slf4j
@Singleton
public class ChannelPoolListener extends ChannelInitializer {

  @Override
  public void initialize(Channel channel) throws IOException {
    channel.exchangeDeclare("judge", BuiltinExchangeType.DIRECT, true);
    channel.queueDeclare("submissions-status", true, false, false, getSubmissionsQueueArguments());
    channel.queueBind("submissions-status", "judge", "status");
    log.info("RabbitMQ exchange and queue were initialized.");
  }

  private Map<String, Object> getSubmissionsQueueArguments() {
    Long oneWeek = Duration.ofDays(7L).toMillis();
    Map<String, Object> queueArguments = new HashMap<>();
    queueArguments.put("x-single-active-consume", true);
    queueArguments.put("x-message-ttl", oneWeek.longValue());
    return queueArguments;
  }
}
```

Thanks for your attention. I'm looking forward to contributing if the team thinks this is a relevant issue.

**Comment by ilopmar** [comment]
Can you please try to annotate your `SubmissionListener` with either `@Replaces(DefaultRabbitListenerExceptionHandler.class)` or `@Replaces(RabbitListenerExceptionHandler.class)`?

**Comment by danbsts** [comment]
It worked, thank you.

I've realized that this wasn't the right listener that handles exceptions from type `MessageListenerException`. Is there a workaround to solve the first error? This [sample project](https://github.com/danbsts/sample-project-mn-rabbit) mocks the described behavior.

**Comment by jameskleeh** [comment]
@danbsts Currently Micronaut requires a connection to be available on startup. Its required in order to register the subscribers, etc on startup.
