### ISSUE TITLE
rabbitlistener network recovery doesn't work

### ISSUE THREAD

**Issue by amillalen** [micronaut-projects/micronaut-rabbitmq#17]
Given a Listener 
``` 
@RabbitListener
class Mndemo2Listener {
    private val logger: Logger =  getLogger(javaClass)
    @Queue("mndemo2")
    fun receive(data: ByteArray, acknowledgement: RabbitAcknowledgement) {
        logger.info("Data size => {}", data.size)
        acknowledgement.ack()
    }
}
``` 
and autorecovery setting 

``` 
rabbitmq:
  uri: ...
  automatic-recovery-enabled: true
  network-recovery-interval: 30000
  requested-heartbeat: 45
``` 

Consumer is terminated when the network is lost for  few minutes ( turn off the network )

rabbitmq client try to autorecover connection and micronaut RabbitMQConsumerAdvice fall in 
``` 
                    @Override
                    public void handleTerminate(String consumerTag) {
                        ConsumerState state = consumerChannels.remove(channel);
                        if (state != null) {
                            state.channelPool.returnChannel(channel);
                            if (LOG.isDebugEnabled()) {
                                LOG.debug("The channel was terminated. The consumer [{}] will no longer receive messages", clientTag);
                            }
                        }
                    }

```
when the network is turn on micronaut show this error
```
13:49:10.120 [pool-2-thread-1] ERROR c.r.c.impl.ForgivingExceptionHandler - Consumer io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice$1@4def99a2 (Mndemo2Listener#void receive(byte[] data,RabbitAcknowledgement acknowledgement)) method handleDelivery for channel AMQChannel(amqp://user@somehost:19082/staging,1) threw an exception for channel AMQChannel(amqp://user@somehost:19082/staging,1)
java.lang.NullPointerException: null
        at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice$ConsumerState.access$802(RabbitMQConsumerAdvice.java:339)
        at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice$1.handleDelivery(RabbitMQConsumerAdvice.java:271)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

and consumer stop to process messages

**Comment by amillalen** [comment]
My workaroud was create a CustomRabbitMQConsumerAdvice and do nothing on handleTerminate. 

`  @Override
                    public void handleTerminate(String consumerTag) {
                        LOG.info("disabled processing of terminate signal for proper network recovering");
                    }
`

Now when the app losses network, the channel isn't removed from the consumerChannels map, and 
 when the system recover the network, it resume processing messages on the queue.

**Comment by grimmjo** [comment]
+1

running into the same problem that after some time the connection get's closed..
The problem is that I can't override the the terminate methode, because it isn't available anymore.

**Comment by mauracwarner** [comment]
+1 We are seeing this issue as well in our Micronaut apps that use RabbitMQ

**Comment by ddierickx** [comment]
Thanks for fixing this. Is there a target release date for 1.1.3?

**Comment by mauracwarner** [comment]
👆 @jameskleeh @graemerocher I am also wondering when we'll be able to pull this fix down into our apps.  Is there a target release date for 1.1.3?

**Comment by ddierickx** [comment]
This is working for us now in 1.1.3, thanks for the help all!
