### ISSUE TITLE
Failed to retrieve a channel pool named [default] to register a listener

### ISSUE THREAD

**Issue by zzsoszz** [micronaut-projects/micronaut-rabbitmq#19]
Connected to the target VM, address: '127.0.0.1:60081', transport: 'socket'
13:19:04.785 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error processing bean [Definition: rabbit.logprocesser.ProductListener] method definition [void receive(byte[] data)]: Failed to retrieve a channel pool named [default] to register a listener
io.micronaut.context.exceptions.BeanContextException: Error processing bean [Definition: rabbit.logprocesser.ProductListener] method definition [void receive(byte[] data)]: Failed to retrieve a channel pool named [default] to register a listener
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:92)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:45)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1543)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2502)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2402)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:615)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:602)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1228)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2320)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:303)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:289)
	at rabbit.logprocesser.Application.main(Application.java:13)
Caused by: io.micronaut.messaging.exceptions.MessageListenerException: Failed to retrieve a channel pool named [default] to register a listener
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:121)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:64)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
	... 15 common frames omitted
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.configuration.rabbitmq.connect.ChannelPool] exists for the given qualifier: @Named('default'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1842)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:577)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:119)
	... 17 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:60081', transport: 'socket'

```java
@Singleton
public class ChannelPoolListener extends ChannelInitializer {

    @Override
    public void initialize(Channel channel) throws IOException {
        //docs/exchange
        Map<String, Object> snakeArgs = new HashMap<>();
        snakeArgs.put("x-match", "all");
        channel.exchangeDeclare("demo", "headers", false);
        channel.queueDeclare("device", false, false, false, null);
        channel.queueBind("demo", "device", "", snakeArgs);
    }

}



@RabbitListener
public class ProductListener {

    List<String> messageLengths = Collections.synchronizedList(new ArrayList<>());
    @Queue("device")
    public void receive(byte[] data) {
        messageLengths.add(new String(data));
        System.out.println("Java received " + data.length + " bytes from RabbitMQ");
    }

}
```

**Comment by jameskleeh** [comment]
Theres not enough information in that stacktrace to go off of. Please upload an example project that reproduces the issue or include the entire stacktrace
