### ISSUE TITLE
ConnectionException with GraalVM

### ISSUE THREAD

**Issue by meredrica** [micronaut-projects/micronaut-rabbitmq#229]
Seems there is an issue when using GraalVM together with the RMQ lib.
Full Stacktrace is below.

### Steps to Reproduce
* Create a new Micronaut App with Kotlin, Gradle, RabbitMQ and GraalVM
* Configure and add a RabbitMQ listener
* Run the native image

### Expected Behaviour

App Connects to RabbitMQ

### Actual Behaviour

Application can't connect

### Environment Information

- **Operating System**: arch/openshift
- **Micronaut Version:** 2.5.1
- **JDK Version:** 
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9)
OpenJDK 64-Bit Server VM (build 11.0.11+9, mixed mode)

### Example Application
https://github.com/meredrica/fluffy-adventure

```
[main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error processing bean [Definition: dispatch.Listener] method definition [void listen(InternalMessage message)]: Failed to retrieve a channel pool named [default] to register a listener
io.micronaut.context.exceptions.BeanContextException: Error processing bean [Definition: dispatch.Listener] method definition [void listen(InternalMessage message)]: Failed to retrieve a channel pool named [default] to register a listener
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:98)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:44)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2036)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3141)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3018)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:786)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:773)
	at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$32(DefaultBeanContext.java:1615)
	at java.util.HashMap.forEach(HashMap.java:1336)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1614)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:234)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2907)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:180)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at dispatch.ApplicationKt.main(Application.kt:6)
Caused by: io.micronaut.messaging.exceptions.MessageListenerException: Failed to retrieve a channel pool named [default] to register a listener
	at io.micronaut.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:124)
	at io.micronaut.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:67)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:95)
	... 15 common frames omitted
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error creating connection to RabbitMQ
	at io.micronaut.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:62)
	at io.micronaut.rabbitmq.connect.$RabbitConnectionFactory$Connection0Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:153)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1285)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:142)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:732)
	at io.micronaut.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:122)
	... 17 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:609)
	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1213)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1170)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1128)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1321)
	at io.micronaut.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:59)

```

**Comment by graemerocher** [comment]
I believe we have Rabbit native image tests that cover this case /cc @ilopmar 

Maybe your configuration is not included in the image

**Comment by ilopmar** [comment]
Yes, we have test for RabbitMQ and GraalVM. Please check this app: https://github.com/micronaut-graal-tests/micronaut-rabbitmq-graal

**Comment by meredrica** [comment]
@ilopmar I had a look and can't see anything special in the repo. The biggest differences are:
* kotlin - but i don't know if that makes any difference. 
* I use the `dockerbuildNative` task since I don't have the GraalVM SDK
I included two seperate scripts in my reproducing repo - one uses the native task, the other does not. if you run both you'll see the graal image having connection issues and the non-native crashing due to the queue not being defined - as expected.

**Comment by meredrica** [comment]
Well, we switched back to Java since we concluded that kotlin is a marketing stunt. Jdk 16 is not supported on graalvm yet so it's not an option for us yet.
Still,the example I provided is not working, you propably look into it.

**Comment by graemerocher** [comment]
We will investigate
