### ISSUE TITLE
@RabbitListener is executed before ChannelInitializer

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-rabbitmq#5]
`RabbitMQConsumerAdvice` is executed before `ChannelInitializer` so when the application tries to subscribe to a queue it doesn't exist yet.
Note that I'm using latest snapshot version built from source.

To reproduce the issue:
- `git clone https://github.com/ilopmar/micronaut-rabbitmq-listener`
- `cd micronaut-rabbitmq-listener`
- `./gradlew run`
- The application fails with:
```
11:37:09.290 [main] ERROR i.m.c.r.i.RabbitMQConsumerAdvice - The channel was closed due to an exception. The consumer [TextListener#String toUpperCase(String text)] will no longer receive messages
11:37:09.294 [main] ERROR i.m.c.r.e.DefaultRabbitListenerExceptionHandler - RabbitMQ consumer [micronaut.rabbitmq.listener.TextListener@2b5825fa] produced an error
io.micronaut.configuration.rabbitmq.exception.RabbitListenerException: An error occurred subscribing to a queue
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:234)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:60)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:45)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1411)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2315)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2220)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:571)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:558)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1119)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:191)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2084)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:169)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:142)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:66)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:273)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:259)
	at micronaut.rabbitmq.listener.Application.main(Application.java:8)
Caused by: java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1378)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicConsume(AutorecoveringChannel.java:532)
	at io.micronaut.configuration.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:160)
	... 17 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'text' in vhost '/', class-id=60, method-id=20)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1372)
	... 19 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'text' in vhost '/', class-id=60, method-id=20)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:516)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:672)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:599)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jameskleeh** [comment]
The class must be a bean
