### ISSUE TITLE
Tests hang when having a listener with non-default ExecutorService

### ISSUE THREAD

**Issue by tobias-bahls** [micronaut-projects/micronaut-rabbitmq#524]
### Expected Behavior

When running integration tests for an application that include RabbitListeners with a custom `ExecutorService`, I expect the ApplicationContext to shut down cleanly.

### Actual Behaviour

After running the tests, this exception is logged and the test runner hangs until it eventually times out:

```
18:08:10.866 [AMQP Connection 0:0:0:0:0:0:0:1:55423] ERROR c.r.c.impl.ForgivingExceptionHandler - An unexpected connection driver error occurred
java.util.concurrent.RejectedExecutionException: Task com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable@32d49f7 rejected from java.util.concurrent.ThreadPoolExecutor@769ec608[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at io.micronaut.scheduling.instrument.InstrumentedExecutor.execute(InstrumentedExecutor.java:69)
	at com.rabbitmq.client.impl.ConsumerWorkService.addWork(ConsumerWorkService.java:88)
	at com.rabbitmq.client.impl.ConsumerDispatcher.execute(ConsumerDispatcher.java:214)
	at com.rabbitmq.client.impl.ConsumerDispatcher.handleShutdownSignal(ConsumerDispatcher.java:173)
	at com.rabbitmq.client.impl.ChannelN.broadcastShutdownSignal(ChannelN.java:278)
	at com.rabbitmq.client.impl.ChannelN.finishProcessShutdownSignal(ChannelN.java:296)
	at com.rabbitmq.client.impl.ChannelN.access$000(ChannelN.java:46)
	at com.rabbitmq.client.impl.ChannelN$2.transformReply(ChannelN.java:600)
	at com.rabbitmq.client.impl.ChannelN$2.transformReply(ChannelN.java:597)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.handleCommand(AMQChannel.java:486)
	at com.rabbitmq.client.impl.RpcContinuationRpcWrapper.complete(RpcContinuationRpcWrapper.java:38)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:200)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:743)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:670)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I suspect this is caused by the `ExecutorService` being shut down before the `RabbitListener`. Note the same setup worked in 3.x

### Steps To Reproduce

Configure a RabbitListener with a non-default threadpool and run integration tests. See example application

### Environment Information

- JDK: OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
- Kotlin 1.8.22

### Example Application

https://github.com/tobias-bahls/micronaut-rabbitmq-test-issue

### Version

4.0.2

**Comment by cutz** [comment]
FWIW I see the same behavior in the context of a CommandLine application that uses a RabbitListener. It appears the executor service is stopped before the channel has handled the shutdown signal.

**Comment by stefanos-kalantzis** [comment]
I have the same exception when I just shutdown a healthy micronaut app with an RMQ listener. It repeats 8 times, and then finally this:

```
12:18:44.835 [Thread-6]  WARN io.micronaut.rabbitmq.connect.RabbitConnectionFactory - Error closing RabbitMQ connection: clean connection shutdown
com.rabbitmq.client.ShutdownSignalException: clean connection shutdown
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1121)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1034)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1018)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.close(AutorecoveringConnection.java:295)
	at io.micronaut.rabbitmq.connect.RabbitConnectionFactory.shutdownConnections(RabbitConnectionFactory.java:83)
	at io.micronaut.rabbitmq.connect.$RabbitConnectionFactory$Definition.dispose(Unknown Source)
	at io.micronaut.inject.DisposableBeanDefinition.dispose(DisposableBeanDefinition.java:44)
	at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1199)
	at io.micronaut.context.DefaultBeanContext.destroyBean(DefaultBeanContext.java:1170)
	at io.micronaut.context.DefaultBeanContext.stop(DefaultBeanContext.java:447)
	at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:202)
	at io.micronaut.http.server.netty.NettyHttpServer.stopInternal(NettyHttpServer.java:641)
	at io.micronaut.http.server.netty.NettyHttpServer.stop(NettyHttpServer.java:342)
	at io.micronaut.http.server.netty.NettyHttpServer.stop(NettyHttpServer.java:329)
	at io.micronaut.http.server.netty.NettyHttpServer.stop(NettyHttpServer.java:104)
	at io.micronaut.runtime.Micronaut.lambda$start$0(Micronaut.java:114)
	at java.base/java.lang.Thread.run(Thread.java:858)
```

and _then_ it shutsdown.

**Comment by larsduelfer** [comment]
Hi all, are there any news on this issue? This currently blocks our upgrade to Micronaut 4 and a solution would be much appreciated. Thanks!

**Comment by sdelamo** [comment]
@jeremyg484 can you investigate this?
