### ISSUE TITLE
Generating Graal reflect.json files makes the application connects to RabbitMQ

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-rabbitmq#8]
If we try to build the Graal native image for an application using RabbitMQ, the process of generating the `reflect.json` file triggers something that makes that application connect to RabbitMQ. If it is not available it fails:

`git clone https://github.com/micronaut-guides/micronaut-rabbitmq`
`cd micronaut-rabbitmq`
`git checkout graal`
`sdk use java 1.0.0-rc-12-grl`
`cd complete/books`
`./gradlew assemble`
`java -cp build/libs/books-0.1.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer`

```
An error occurred analyzing class requirements: Error creating connection to RabbitMQ
io.micronaut.context.exceptions.BeanInstantiationException: Error creating connection to RabbitMQ
	at io.micronaut.configuration.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:53)
	at io.micronaut.configuration.rabbitmq.connect.$RabbitConnectionFactory$ConnectionDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1366)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1948)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1669)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1649)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:922)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:977)
	at io.micronaut.configuration.rabbitmq.connect.$DefaultChannelPoolDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1366)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1948)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1669)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1649)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:922)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:977)
	at io.micronaut.configuration.rabbitmq.intercept.$RabbitMQConsumerAdviceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1366)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2315)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2243)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:778)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:548)
	at io.micronaut.graal.reflect.GraalClassLoadingAnalyzer.main(GraalClassLoadingAnalyzer.java:81)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1106)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1021)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1213)
	at io.micronaut.configuration.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:51)
	... 21 more
```

**Comment by graemerocher** [comment]
Another reason we should work towards removing that step since it has to run the application to generate it

**Comment by graemerocher** [comment]
Unrelated to the project, has to be solved by build type stuff
